//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hijos
    {
        public int idhijos { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public System.DateTime fechaNac { get; set; }
        public int idmitabla { get; set; }
        public string direccion { get; set; }
        public int edad { get; set; }
        public string sexo { get; set; }
    
        public virtual mitabla mitabla { get; set; }
    }
}
